documents_ai = "Do not Remove this First line of text. In windows it will make your app not to access Replicate API TOken below resulting in Error in your app"
REPLICATE_API_TOKEN = "r8_PD7gLbVL8EW97flXUQyv6bQxx2V9TOE2Koksd"
